### ISSUE TITLE
qtcreator: build fails with 'Source dir not provided'

### ISSUE THREAD

**Issue by rainboh** [prozum/meson-cmake-wrapper#11]
Opened https://github.com/prozum/meson-cmake-wrapper/tree/master/test/project in qtcreator 4.8.0 and 4.6.2.

meson 0.49.0

mcw 0.3.0

Building the project fails with
~~~
2019-01-02 14:08:46,986 - CMake Wrapper: Source dir not provided
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mcw/cmake.py", line 59, in run
    getattr(self, self.command + '_cmd')()
  File "/usr/local/lib/python3.6/dist-packages/mcw/cmake.py", line 192, in build_cmd
    self.load_cache_entries()
  File "/usr/local/lib/python3.6/dist-packages/mcw/cmake.py", line 406, in load_cache_entries
    self.init_cache_entries()
  File "/usr/local/lib/python3.6/dist-packages/mcw/cmake.py", line 325, in init_cache_entries
    raise Exception('Source dir not provided')
Exception: Source dir not provided
~~~

To exclude I did some usage mistakes here are the executed steps:
- qtcreator options setup to use mcw
- qtcreator -> file -> open file or project -> CMakeLists.txt -> click btn 'configure project'
- qtcreator 'general messages' pane displayed
~~~
Running "/usr/local/bin/mcw -E server --pipe=/tmp/cmake-.WIFNFE/socket --experimental" in /tmp/QtCreator-IxKtCp/qtc-cmake-rucuZcVr.
QLocalSocket::connectToServer: Invalid name
Starting to parse CMake project, using: "-DCMAKE_CXX_COMPILER:STRING=/usr/lib/ccache/g++", "-DCMAKE_C_COMPILER:STRING=/usr/lib/ccache/gcc", "-DCMAKE_PREFIX_PATH:STRING=/usr", "-DQT_QMAKE_EXECUTABLE:STRING=/usr/lib/qt5/bin/qmake".
Configuring done
Generating done
CMake Project was parsed successfully.
~~~
- qtcreator 'project view' displayed \<Headers\> structure with all header files, but no .cpp files
- qtcreator -> build -> build project
- qtcreator 'general messages' pane displayed
~~~
Running "/usr/local/bin/mcw -E server --pipe=/tmp/cmake-.ByYSql/socket --experimental" in /home/user/git/meson-cmake-wrapper/test/build-project-Desktop-Default.
QLocalSocket::connectToServer: Invalid name
Starting to parse CMake project, using: "-DCMAKE_CXX_COMPILER:STRING=/usr/lib/ccache/g++", "-DCMAKE_C_COMPILER:STRING=/usr/lib/ccache/gcc", "-DCMAKE_PREFIX_PATH:STRING=/usr", "-DQT_QMAKE_EXECUTABLE:STRING=/usr/lib/qt5/bin/qmake".
Configuring done
Generating done
CMake Project was parsed successfully.
~~~
- build failed with above reported 'Source dir not provided' msg

**Comment by rainboh** [comment]
Thanks for fixing this. Just tried with my project and I can confirm that the 'Source dir not provided' issue is gone.

What still remains is
* qtcreator 'project view' displayed <Headers> structure with all header files, but no .cpp files

Is this expected, as maybe displaying src files is not supported yet, or is it another issue and should I open a new ticket for that ?

**Comment by overby-me** [comment]
This is not expected. Please open another issue.
