### ISSUE TITLE
qtcreator: cpp files not shown in project view

### ISSUE THREAD

**Issue by rainboh** [prozum/meson-cmake-wrapper#13]
Opened https://github.com/prozum/meson-cmake-wrapper/tree/master/test/project in qtcreator 4.6.2.

meson 0.49.0

mcw 0.3.2

After loading the project only header files are shown.
Projects .cpp files are missing.

**Comment by overby-me** [comment]
I'm closing the issue since the project will be archived. Feel free to create a fork.
