### ISSUE TITLE
CLion not detecting sources

### ISSUE THREAD

**Issue by pinkwah** [prozum/meson-cmake-wrapper#2]
Trying to get this to work with `CLion 2018.2.2` and `meson 0.47.2`.

CLion correctly detects and configures executable targets. However, it cannot detect the sources as being part of the project.

That is, consider the following `meson.build` with a trivial `main.cpp`.
```meson
project('hello', 'cpp')
executable('hello', sources : 'main.cpp')
```

 CLion manages to compile and run the `hello` executable, but it doesn't recognise `main.cpp`.

**Comment by overby-me** [comment]
Sorry for late response. If you still have problems please open another issue.
