### ISSUE TITLE
New maintainer needed

### ISSUE THREAD

**Issue by overby-me** [prozum/meson-cmake-wrapper#22]
I started using Emacs, so I'm not interested in maintaining or using this project anymore.

So I'm willing to transfer giving maintainership to anybody willing.

Mikhail Elhimov actually volunteered, but he has not done any work what so ever. 

So please write on this thread, if you are interested in maintaining this project.

**Comment by Yamakuzure** [comment]
That's unfortunate.
I am no Python programmer, and my project list is already too long for my limited spare time. 

So I will fork it, but won't be able to take official maintainership, sorry. (At least at the moment)

**Comment by Yamakuzure** [comment]
If you could at least merge PRs, that would be great!
