### ISSUE TITLE
CLion: Compiler arguments (such as -I<Include directory>) not being passed for CLion to consume

### ISSUE THREAD

**Issue by pinkwah** [prozum/meson-cmake-wrapper#3]
Minimal bug example: https://github.com/dotfloat/mcw-clion-bug-1

Here I'm including a non-standard directory `include`. I expect CLion to detect that the file `"inc.hh"` is located in this custom directory, but it doesn't. When using cmake with the equivalent `CMakeLists.txt`, it works as expected.

It should maybe be noted that the project compiles and runs fine.

Thanks!

**Comment by pinkwah** [comment]
Minimal-er bug example: https://github.com/dotfloat/mcw-clion-bug-2

Here we're passing a C preprocessor definition `-DHELLO_WORLD=1`. However, CLion doesn't know about this when using `mcw`, and underlines the `#error` line.

Again, it compiles and runs as expected.

**Comment by overby-me** [comment]
I will look at it but I cannot promise anything. I've had a hard time figuring out how CLion fetches compile flags from cmake. But thanks for examples! :)
