### ISSUE TITLE
CLion header includes

### ISSUE THREAD

**Issue by lgrahl** [prozum/meson-cmake-wrapper#6]
I tried a couple of Meson C projects but I'm unable to get CLion to detect the include directories. Thus, the included file's functions cannot be auto-completed. @noverby do you have an idea what might be the problem?

**Comment by overby-me** [comment]
Can you push a minimal Meson project to Github that has the problem?

**Comment by lgrahl** [comment]
There you go: https://github.com/lgrahl/meson-cmake-wrapper-clion-test

**Comment by lgrahl** [comment]
But FWIW this issue also includes `printf` and friends. I'm not getting auto-completion for them either.

**Comment by lgrahl** [comment]
That was all? :sweat_smile: Well, I'll take it! Cheers!

**Comment by overby-me** [comment]
Yeah just a small typo. :)

**Comment by lgrahl** [comment]
Late feedback: Works great! This project is a hidden gem and helped me in porting [RAWRTC and all its dependencies](https://github.com/rawrtc/) to Meson. :+1:
