### ISSUE TITLE
support for xcode?

### ISSUE THREAD

**Issue by asartori86** [prozum/meson-cmake-wrapper#8]
Hi,
would that be possible? How difficult would be?

**Comment by overby-me** [comment]
Meson supports generating XCode projects. Why would you need meson-cmake-wrapper to generate XCode projects?

**Comment by asartori86** [comment]
well, not really. It might work for a trivial application. I tested on different projects where I am involved and I always get errors using `meson --backend=xcode`

**Comment by asartori86** [comment]
@noverby, just for reference

https://github.com/mesonbuild/meson/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+xcode

**Comment by overby-me** [comment]
As for your questions:
> would that be possible? How difficult would be?

I don't know. I have never done anything serious with XCode since I don't use Apple products.
If you want to work on it I wouldn't mind merging a working XCode backend.

On the other hand it would probably be better/easier to fix the issues in Meson.

**Comment by overby-me** [comment]
I'm closing the issue since the project will be archived. Feel free to create a fork.
